Add controllers
Fyodor-Mityanin/java-shareit pull request #1
Opened 2022-12-30 18:35 UTC by Fyodor-Mityanin

2023-01-01 21:57 UTC, alexache requested changes

2023-01-01 21:57 UTC, alexache commented on pom.xml
> +			<groupId>org.springframework.boot</groupId>
Разве jdbc требовался в этом спринте?

2023-01-01 21:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +            JdbcTemplate jdbcTemplate
Это немного ненужные переносы строк

2023-01-01 21:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            if (itemDto.getAvailable() != null) {
Это какое-то усложнение. Можно запросить прошлое состояние товара (вместо валидации о его существовании) и поменять только те поля, которые присутствуют в dto

2023-01-01 21:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (text.isBlank()) {
Такие валидации можно делать еще в контроллере через аннотации

2023-01-01 21:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemValidation.java
> +public class ItemValidation {
(опционально) ту же задачу можно решать валидациями на полях в ДТО (в том числе делать различное поведение для создания и обновления)

2023-01-01 21:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    private final UserRepository userRepository;
Очень нежелательно: чтобы у маппера были какие либо зависимости. Методы маппера должны быть статическими

2023-01-01 21:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        User user = userRepository.getUserById(itemDto.getOwner()).orElseThrow();
Это лучше передавать как аргумент метода, а не искать внутри маппера

2023-01-01 21:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Long> deleteOneById(@PathVariable long id) {
Для чего возвращать long? еще и с ResponseEntity?

2023-01-01 21:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        if (userDto.getEmail() != null && userDto.getName() != null) {
Как и в случае товаров это выглядит усложнением

2023-01-01 21:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserValidation.java
> +        if (!userDto.getEmail().matches(REGEX_PATTERN)) {
Лучше бы через аннотации на ДТО :)

2023-01-01 21:57 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
> +    public UserDto toDto(User user) {
почему бы не сделать все поля статическими, как и ринято у мапперов, и не создавать объекты

2023-01-11 09:39 UTC, Fyodor-Mityanin commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +            JdbcTemplate jdbcTemplate
Такой перенос я делаю что бы можно быстро по бинам перемещаться в идее, там на против каждой строки - ссылка на ээтот бин получается

2023-01-11 09:42 UTC, Fyodor-Mityanin commented on pom.xml
> +			<groupId>org.springframework.boot</groupId>
хранить данные нужно было внутри приложения?

2023-01-13 11:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +            JdbcTemplate jdbcTemplate
Если я правильно понял о чем ты, то идеа и так справится со вставкой такого контекста и без доп строки

2023-01-13 12:25 UTC, alexache approved these changes

2023-01-13 12:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        ItemDto updatedItemDto = ItemMapper.toDto(updatedItem);
возможно было бы достаточно и просто модели (не дто) для сравнения

2023-01-13 12:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserValidation.java
>          if (userDto.getEmail() == null && userDto.getName() == null) {
это все же возможно и на дто объекте через аннотации

2023-01-15 15:11 UTC, merged